#!/bin/bash
set -e

test_complete_build() {
  npm run build

  themes=(biz high-contrast hipster translucid)

  for theme in "${themes[@]}"
  do
    test_theme_build $theme
  done

  exit 0
}

test_theme_build() {
  local test_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  local project_dir="$(dirname ${test_dir})"
  local expanded_file="${project_dir}/dist/tooltippy--$1.css"
  local debug_file="${project_dir}/dist/tooltippy--$1.debug.css"
  local min_file="${project_dir}/dist/tooltippy--$1.min.css"

  if [ ! -e ${expanded_file} ] || [ ! -e ${debug_file} ] || [ ! -e ${min_file} ]
  then
    exit 1
  fi
}

test_complete_build
